## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##

coreo_aws_advisor_alert "myalert" do
  action :define
  service :redshift
  link "N/A"
  display_name "Redshift short snapshot retention period"
  description "sign of a redshift newbie"
  category "Dataloss"
  suggested_action "lengthen it dumbass"
  level "Warning"
  objectives ["clusters"]
  id_map "object.clusters.cluster_identifier"
  audit_objects ["object.clusters.automated_snapshot_retention_period"]
  operators ["<="]
  alert_when [10]
end

coreo_aws_advisor_redshift "" do
  action :advise
  alerts ["myalert"]
end

coreo_uni_util_notify "advise-redshift" do
  action :notify
  type 'email'
  allow_empty true
  send_on "always"
  payload 'COMPOSITE::coreo_uni_util_notify.advise-redshift.report'
  payload_type "json"
  endpoint ({
      :to => 'jason@cloudcoreo.com', :subject => 'test alert'
  })
end